In [1]:
pip install yfinance

Collecting yfinance
  Downloading yfinance-0.2.66-py2.py3-none-any.whl.metadata (6.0 kB)
Requirement already satisfied: pandas>=1.3.0 in c:\users\usuario\anaconda3\lib\site-packages (from yfinance) (2.2.2)
Requirement already satisfied: numpy>=1.16.5 in c:\users\usuario\anaconda3\lib\site-packages (from yfinance) (1.26.4)
Requirement already satisfied: requests>=2.31 in c:\users\usuario\anaconda3\lib\site-packages (from yfinance) (2.32.3)
Collecting multitasking>=0.0.7 (from yfinance)
  Downloading multitasking-0.0.12.tar.gz (19 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Requirement already satisfied: platformdirs>=2.0.0 in c:\users\usuario\anaconda3\lib\site-packages (from yfinance) (3.10.0)
Requirement already satisfied: pytz>=2022.5 in c:\users\usuario\anaconda3\lib\site-packages (from yfinance) (2024.1)
Requirement already satisfied: frozendict>=2.3.4 in c:\users\usuario\anaconda3\lib\site-packages (from yfinance) (2.4.2)
Collecting peewee>=3.16.2 (from yfinance)
  Downloading peewee-3.18.3.tar.gz (3.0 MB)
     ---------------------------------------- 0.0/3.0 MB ? eta -:--:--
     ---------------------------------------- 3.0/3.0 MB 43.9 MB/s eta 0:00:00
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Requirement already satisfied: beautifulsoup4>=4.11.1 in c:\users\usuario\anaconda3\lib\site-packages (from yfinance) (4.12.3)
Collecting curl_cffi>=0.7 (from yfinance)
  Downloading curl_cffi-0.14.0-cp39-abi3-win_amd64.whl.metadata (15 kB)
Requirement already satisfied: protobuf>=3.19.0 in c:\users\usuario\anaconda3\lib\site-packages (from yfinance) (6.32.1)
Collecting websockets>=13.0 (from yfinance)
  Downloading websockets-15.0.1-cp312-cp312-win_amd64.whl.metadata (7.0 kB)
Requirement already satisfied: soupsieve>1.2 in c:\users\usuario\anaconda3\lib\site-packages (from beautifulsoup4>=4.11.1->yfinance) (2.5)
Requirement already satisfied: cffi>=1.12.0 in c:\users\usuario\anaconda3\lib\site-packages (from curl_cffi>=0.7->yfinance) (1.17.1)
Requirement already satisfied: certifi>=2024.2.2 in c:\users\usuario\anaconda3\lib\site-packages (from curl_cffi>=0.7->yfinance) (2025.1.31)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\usuario\anaconda3\lib\site-packages (from pandas>=1.3.0->yfinance) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in c:\users\usuario\anaconda3\lib\site-packages (from pandas>=1.3.0->yfinance) (2023.3)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\usuario\anaconda3\lib\site-packages (from requests>=2.31->yfinance) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\usuario\anaconda3\lib\site-packages (from requests>=2.31->yfinance) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\usuario\anaconda3\lib\site-packages (from requests>=2.31->yfinance) (2.2.3)
Requirement already satisfied: pycparser in c:\users\usuario\anaconda3\lib\site-packages (from cffi>=1.12.0->curl_cffi>=0.7->yfinance) (2.21)
Requirement already satisfied: six>=1.5 in c:\users\usuario\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas>=1.3.0->yfinance) (1.16.0)
Downloading yfinance-0.2.66-py2.py3-none-any.whl (123 kB)
Downloading curl_cffi-0.14.0-cp39-abi3-win_amd64.whl (1.7 MB)
   ---------------------------------------- 0.0/1.7 MB ? eta -:--:--
   ---------------------------------------- 1.7/1.7 MB 30.1 MB/s eta 0:00:00
Downloading websockets-15.0.1-cp312-cp312-win_amd64.whl (176 kB)
Building wheels for collected packages: multitasking, peewee
  Building wheel for multitasking (setup.py): started
  Building wheel for multitasking (setup.py): finished with status 'done'
  Created wheel for multitasking: filename=multitasking-0.0.12-py3-none-any.whl size=15617 sha256=513c5df63af29df4aebf55fce2fd3158ee9114c2e9ac050918db804171f5c1ef
  Stored in directory: c:\users\usuario\appdata\local\pip\cache\wheels\cc\bd\6f\664d62c99327abeef7d86489e6631cbf45b56fbf7ef1d6ef00
  Building wheel for peewee (pyproject.toml): started
  Building wheel for peewee (pyproject.toml): finished with status 'done'
  Created wheel for peewee: filename=peewee-3.18.3-py3-none-any.whl size=139181 sha256=8f1ebf68053a1b47fb3bd9800891e9f4a90ff9192b98c9415d2efc328cbbedee
  Stored in directory: c:\users\usuario\appdata\local\pip\cache\wheels\e2\48\b6\675a31c56e50b8b343e1ffbb1d9209f0d95025e2cfa0bbeeed
Successfully built multitasking peewee
Installing collected packages: peewee, multitasking, websockets, curl_cffi, yfinance
Successfully installed curl_cffi-0.14.0 multitasking-0.0.12 peewee-3.18.3 websockets-15.0.1 yfinance-0.2.66
Note: you may need to restart the kernel to use updated packages.

In [1]:
import yfinance as yf

In [133]:
import pandas as pd

In [159]:
dat = yf.Ticker("AAPL")

In [161]:
apl = dat.history(period='5y',auto_adjust= False)

In [59]:
msft

,Open,High,Low,Close,Adj Close,Volume,Dividends,Stock Splits
Date,,,,,,,,
2020-12-17 00:00:00-05:00,219.869995,220.889999,217.919998,219.419998,210.542236,32515800,0.0,0.0
2020-12-18 00:00:00-05:00,218.589996,219.690002,216.020004,218.589996,209.745819,63354900,0.0,0.0
2020-12-21 00:00:00-05:00,217.550003,224.000000,217.279999,222.589996,213.583923,37181900,0.0,0.0
2020-12-22 00:00:00-05:00,222.690002,225.630005,221.850006,223.940002,214.879318,22612200,0.0,0.0
2020-12-23 00:00:00-05:00,223.110001,223.559998,220.800003,221.020004,212.077499,18699600,0.0,0.0
...,...,...,...,...,...,...,...,...
2025-12-11 00:00:00-05:00,476.630005,486.029999,475.859985,483.470001,483.470001,24669200,0.0,0.0
2025-12-12 00:00:00-05:00,479.820007,482.450012,476.339996,478.529999,478.529999,21248100,0.0,0.0
2025-12-15 00:00:00-05:00,480.100006,480.720001,472.519989,474.820007,474.820007,23727700,0.0,0.0
2025-12-16 00:00:00-05:00,471.910004,477.890015,470.880005,476.390015,476.390015,20682600,0.0,0.0
2025-12-17 00:00:00-05:00,476.904999,479.000000,475.220001,478.600006,478.600006,9481990,0.0,0.0

In [61]:
msft['SMA21'] = msft['Adj Close'].rolling(21).mean()

In [63]:
msft

,Open,High,Low,Close,Adj Close,Volume,Dividends,Stock Splits,SMA21
Date,,,,,,,,,
2020-12-17 00:00:00-05:00,219.869995,220.889999,217.919998,219.419998,210.542236,32515800,0.0,0.0,NaN
2020-12-18 00:00:00-05:00,218.589996,219.690002,216.020004,218.589996,209.745819,63354900,0.0,0.0,NaN
2020-12-21 00:00:00-05:00,217.550003,224.000000,217.279999,222.589996,213.583923,37181900,0.0,0.0,NaN
2020-12-22 00:00:00-05:00,222.690002,225.630005,221.850006,223.940002,214.879318,22612200,0.0,0.0,NaN
2020-12-23 00:00:00-05:00,223.110001,223.559998,220.800003,221.020004,212.077499,18699600,0.0,0.0,NaN
...,...,...,...,...,...,...,...,...,...
2025-12-11 00:00:00-05:00,476.630005,486.029999,475.859985,483.470001,483.470001,24669200,0.0,0.0,488.093871
2025-12-12 00:00:00-05:00,479.820007,482.450012,476.339996,478.529999,478.529999,21248100,0.0,0.0,486.586482
2025-12-15 00:00:00-05:00,480.100006,480.720001,472.519989,474.820007,474.820007,23727700,0.0,0.0,485.275540
2025-12-16 00:00:00-05:00,471.910004,477.890015,470.880005,476.390015,476.390015,20682600,0.0,0.0,483.711879
2025-12-17 00:00:00-05:00,476.904999,479.000000,475.220001,478.600006,478.600006,9481990,0.0,0.0,482.381311

In [65]:
msft = msft.dropna()
msft

,Open,High,Low,Close,Adj Close,Volume,Dividends,Stock Splits,SMA21
Date,,,,,,,,,
2021-01-19 00:00:00-05:00,213.750000,216.979996,212.630005,216.440002,207.682800,30480900,0.0,0.0,210.099914
2021-01-20 00:00:00-05:00,217.699997,225.789993,217.289993,224.339996,215.263138,37777300,0.0,0.0,210.324719
2021-01-21 00:00:00-05:00,224.699997,226.300003,222.419998,224.970001,215.867676,30709400,0.0,0.0,210.616236
2021-01-22 00:00:00-05:00,227.080002,230.070007,225.800003,225.949997,216.808014,30172700,0.0,0.0,210.769764
2021-01-25 00:00:00-05:00,229.119995,229.779999,224.220001,229.529999,220.243179,33152100,0.0,0.0,211.025186
...,...,...,...,...,...,...,...,...,...
2025-12-11 00:00:00-05:00,476.630005,486.029999,475.859985,483.470001,483.470001,24669200,0.0,0.0,488.093871
2025-12-12 00:00:00-05:00,479.820007,482.450012,476.339996,478.529999,478.529999,21248100,0.0,0.0,486.586482
2025-12-15 00:00:00-05:00,480.100006,480.720001,472.519989,474.820007,474.820007,23727700,0.0,0.0,485.275540
2025-12-16 00:00:00-05:00,471.910004,477.890015,470.880005,476.390015,476.390015,20682600,0.0,0.0,483.711879
2025-12-17 00:00:00-05:00,476.904999,479.000000,475.220001,478.600006,478.600006,9481990,0.0,0.0,482.381311

In [69]:
array =type(["hola","chau"])
array

list

In [71]:
mi_lista = ["hola", "chau"]

print(type(mi_lista))

<class 'list'>

In [77]:
msft.describe()

,Open,High,Low,Close,Adj Close,Volume,Dividends,Stock Splits,SMA21
count,1236.000000,1236.000000,1236.000000,1236.000000,1236.000000,1.236000e+03,1236.000000,1236.0,1236.000000
mean,348.653394,351.846238,345.292823,348.718325,342.777164,2.554240e+07,0.011416,0.0,340.569226
std,86.311171,86.510230,85.822179,86.168127,88.397216,1.003655e+07,0.089987,0.0,87.819934
min,213.750000,216.979996,212.630005,214.250000,207.682800,7.164500e+06,0.000000,0.0,210.099914
25%,273.267509,277.112511,269.607491,273.054993,266.233932,1.892720e+07,0.000000,0.0,260.577360
50%,332.069992,335.165009,328.444992,331.264999,323.989334,2.316640e+07,0.000000,0.0,321.504262
75%,418.282501,421.757500,414.644989,417.542496,413.796051,2.949882e+07,0.000000,0.0,414.948756
max,555.229980,555.450012,540.770020,542.070007,541.057373,9.042890e+07,0.910000,0.0,520.559993

In [79]:
msft.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 1236 entries, 2021-01-19 00:00:00-05:00 to 2025-12-17 00:00:00-05:00
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Open          1236 non-null   float64
 1   High          1236 non-null   float64
 2   Low           1236 non-null   float64
 3   Close         1236 non-null   float64
 4   Adj Close     1236 non-null   float64
 5   Volume        1236 non-null   int64
 6   Dividends     1236 non-null   float64
 7   Stock Splits  1236 non-null   float64
 8   SMA21         1236 non-null   float64
dtypes: float64(8), int64(1)
memory usage: 96.6 KB

In [97]:
list(msft.columns)

['Open',
 'High',
 'Low',
 'Close',
 'Adj Close',
 'Volume',
 'Dividends',
 'Stock Splits',
 'SMA21']

In [119]:
msft = msft

In [121]:
msft

,Date,Open,High,Low,Close,Adj Close,Volume,Dividends,Stock Splits,SMA21
0,2021-01-19 00:00:00-05:00,213.750000,216.979996,212.630005,216.440002,207.682800,30480900,0.0,0.0,210.099914
1,2021-01-20 00:00:00-05:00,217.699997,225.789993,217.289993,224.339996,215.263138,37777300,0.0,0.0,210.324719
2,2021-01-21 00:00:00-05:00,224.699997,226.300003,222.419998,224.970001,215.867676,30709400,0.0,0.0,210.616236
3,2021-01-22 00:00:00-05:00,227.080002,230.070007,225.800003,225.949997,216.808014,30172700,0.0,0.0,210.769764
4,2021-01-25 00:00:00-05:00,229.119995,229.779999,224.220001,229.529999,220.243179,33152100,0.0,0.0,211.025186
...,...,...,...,...,...,...,...,...,...,...
1231,2025-12-11 00:00:00-05:00,476.630005,486.029999,475.859985,483.470001,483.470001,24669200,0.0,0.0,488.093871
1232,2025-12-12 00:00:00-05:00,479.820007,482.450012,476.339996,478.529999,478.529999,21248100,0.0,0.0,486.586482
1233,2025-12-15 00:00:00-05:00,480.100006,480.720001,472.519989,474.820007,474.820007,23727700,0.0,0.0,485.275540
1234,2025-12-16 00:00:00-05:00,471.910004,477.890015,470.880005,476.390015,476.390015,20682600,0.0,0.0,483.711879
1235,2025-12-17 00:00:00-05:00,476.904999,479.000000,475.220001,478.600006,478.600006,9481990,0.0,0.0,482.381311

In [105]:
msft.Date

0      2021-01-19 00:00:00-05:00
1      2021-01-20 00:00:00-05:00
2      2021-01-21 00:00:00-05:00
3      2021-01-22 00:00:00-05:00
4      2021-01-25 00:00:00-05:00
                  ...
1231   2025-12-11 00:00:00-05:00
1232   2025-12-12 00:00:00-05:00
1233   2025-12-15 00:00:00-05:00
1234   2025-12-16 00:00:00-05:00
1235   2025-12-17 00:00:00-05:00
Name: Date, Length: 1236, dtype: datetime64[ns, America/New_York]

In [109]:
msdft = msft.set_index('Date')

In [113]:
msdft.index

DatetimeIndex(['2021-01-19 00:00:00-05:00', '2021-01-20 00:00:00-05:00',
               '2021-01-21 00:00:00-05:00', '2021-01-22 00:00:00-05:00',
               '2021-01-25 00:00:00-05:00', '2021-01-26 00:00:00-05:00',
               '2021-01-27 00:00:00-05:00', '2021-01-28 00:00:00-05:00',
               '2021-01-29 00:00:00-05:00', '2021-02-01 00:00:00-05:00',
               ...
               '2025-12-04 00:00:00-05:00', '2025-12-05 00:00:00-05:00',
               '2025-12-08 00:00:00-05:00', '2025-12-09 00:00:00-05:00',
               '2025-12-10 00:00:00-05:00', '2025-12-11 00:00:00-05:00',
               '2025-12-12 00:00:00-05:00', '2025-12-15 00:00:00-05:00',
               '2025-12-16 00:00:00-05:00', '2025-12-17 00:00:00-05:00'],
              dtype='datetime64[ns, America/New_York]', name='Date', length=1236, freq=None)

In [115]:
msdft.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 1236 entries, 2021-01-19 00:00:00-05:00 to 2025-12-17 00:00:00-05:00
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Open          1236 non-null   float64
 1   High          1236 non-null   float64
 2   Low           1236 non-null   float64
 3   Close         1236 non-null   float64
 4   Adj Close     1236 non-null   float64
 5   Volume        1236 non-null   int64
 6   Dividends     1236 non-null   float64
 7   Stock Splits  1236 non-null   float64
 8   SMA21         1236 non-null   float64
dtypes: float64(8), int64(1)
memory usage: 96.6 KB

In [117]:
msdft.shape

(1236, 9)

In [163]:
apl

,Open,High,Low,Close,Adj Close,Volume,Dividends,Stock Splits
Date,,,,,,,,
2020-12-18 00:00:00-05:00,128.960007,129.100006,126.120003,126.660004,123.297470,192541500,0.0,0.0
2020-12-21 00:00:00-05:00,125.019997,128.309998,123.449997,128.229996,124.825783,121251600,0.0,0.0
2020-12-22 00:00:00-05:00,131.610001,134.410004,129.649994,131.880005,128.378906,168904800,0.0,0.0
2020-12-23 00:00:00-05:00,132.160004,132.429993,130.779999,130.960007,127.483330,88223700,0.0,0.0
2020-12-24 00:00:00-05:00,131.320007,133.460007,131.100006,131.970001,128.466522,54930100,0.0,0.0
...,...,...,...,...,...,...,...,...
2025-12-11 00:00:00-05:00,279.100006,279.589996,273.809998,278.029999,278.029999,33248000,0.0,0.0
2025-12-12 00:00:00-05:00,277.899994,279.220001,276.820007,278.279999,278.279999,39532900,0.0,0.0
2025-12-15 00:00:00-05:00,280.149994,280.149994,272.839996,274.109985,274.109985,50409100,0.0,0.0
2025-12-16 00:00:00-05:00,272.820007,275.500000,271.790009,274.609985,274.609985,37648600,0.0,0.0
2025-12-17 00:00:00-05:00,275.010010,276.160004,271.690002,271.839996,271.839996,49406521,0.0,0.0

In [231]:
datos = yf.download('AAPL', period='1mo', auto_adjust =False)

print(datos.head())

[*********************100%***********************]  1 of 1 completed

Price        Adj Close       Close        High         Low        Open  \
Ticker            AAPL        AAPL        AAPL        AAPL        AAPL
Date
2025-11-18  267.440002  267.440002  270.709991  265.320007  269.989990
2025-11-19  268.559998  268.559998  272.209991  265.500000  265.529999
2025-11-20  266.250000  266.250000  275.429993  265.920013  270.829987
2025-11-21  271.489990  271.489990  273.329987  265.670013  265.950012
2025-11-24  275.920013  275.920013  277.000000  270.899994  270.899994

Price         Volume
Ticker          AAPL
Date
2025-11-18  45677300
2025-11-19  40424500
2025-11-20  45823600
2025-11-21  59030800
2025-11-24  65585800

In [233]:
datos = datos.columns.droplevel('Ticker')

In [235]:
datos

Index(['Adj Close', 'Close', 'High', 'Low', 'Open', 'Volume'], dtype='object', name='Price')

In [237]:
# 1. Vuelve a cargar la data (porque 'datos' ahora es solo una lista y perdiste la info)
datos = yf.download('AAPL', period='1mo', auto_adjust=False)

# 2. EL FIX: Asigna el cambio a 'datos.columns'
datos.columns = datos.columns.droplevel('Ticker') 

# 3. (Opcional) Para que quede perfecto y no diga "Price" arriba a la izquierda
datos.columns.name = None

# Ahora sí, imprime para ver la tabla
print(datos.head())

[*********************100%***********************]  1 of 1 completed

             Adj Close       Close        High         Low        Open  \
Date
2025-11-18  267.440002  267.440002  270.709991  265.320007  269.989990
2025-11-19  268.559998  268.559998  272.209991  265.500000  265.529999
2025-11-20  266.250000  266.250000  275.429993  265.920013  270.829987
2025-11-21  271.489990  271.489990  273.329987  265.670013  265.950012
2025-11-24  275.920013  275.920013  277.000000  270.899994  270.899994

              Volume
Date
2025-11-18  45677300
2025-11-19  40424500
2025-11-20  45823600
2025-11-21  59030800
2025-11-24  65585800

In [239]:
datos

,Adj Close,Close,High,Low,Open,Volume
Date,,,,,,
2025-11-18,267.440002,267.440002,270.709991,265.320007,269.989990,45677300
2025-11-19,268.559998,268.559998,272.209991,265.500000,265.529999,40424500
2025-11-20,266.250000,266.250000,275.429993,265.920013,270.829987,45823600
2025-11-21,271.489990,271.489990,273.329987,265.670013,265.950012,59030800
2025-11-24,275.920013,275.920013,277.000000,270.899994,270.899994,65585800
2025-11-25,276.970001,276.970001,280.380005,275.250000,275.269989,46914200
2025-11-26,277.549988,277.549988,279.529999,276.630005,276.959991,33431400
2025-11-28,278.850006,278.850006,279.000000,275.989990,277.260010,20135600
2025-12-01,283.100006,283.100006,283.420013,276.140015,278.010010,46587700
2025-12-02,286.190002,286.190002,287.399994,282.630005,283.000000,53669500
2025-12-03,284.149994,284.149994,288.619995,283.299988,286.200012,43538700
2025-12-04,280.700012,280.700012,284.730011,278.589996,284.100006,43989100
2025-12-05,278.779999,278.779999,281.140015,278.049988,280.540009,47265800
2025-12-08,277.890015,277.890015,279.670013,276.149994,278.130005,38211800
2025-12-09,277.179993,277.179993,280.029999,276.920013,278.160004,32193300
2025-12-10,278.779999,278.779999,279.750000,276.440002,277.750000,33038300
2025-12-11,278.029999,278.029999,279.589996,273.809998,279.100006,33248000
2025-12-12,278.279999,278.279999,279.220001,276.820007,277.899994,39532900
2025-12-15,274.109985,274.109985,280.149994,272.839996,280.149994,50409100
2025-12-16,274.609985,274.609985,275.500000,271.790009,272.820007,37648600
2025-12-17,271.839996,271.839996,276.160004,271.690002,275.010010,49406521

In [241]:
datos.Close

Date
2025-11-18    267.440002
2025-11-19    268.559998
2025-11-20    266.250000
2025-11-21    271.489990
2025-11-24    275.920013
2025-11-25    276.970001
2025-11-26    277.549988
2025-11-28    278.850006
2025-12-01    283.100006
2025-12-02    286.190002
2025-12-03    284.149994
2025-12-04    280.700012
2025-12-05    278.779999
2025-12-08    277.890015
2025-12-09    277.179993
2025-12-10    278.779999
2025-12-11    278.029999
2025-12-12    278.279999
2025-12-15    274.109985
2025-12-16    274.609985
2025-12-17    271.839996
Name: Close, dtype: float64